sudo: true
language: cpp
services:
- docker
before_install:
- docker run -d --name build_img -v $(pwd):/travis voidlinux/voidlinux tail -f /dev/null
- docker ps
install:
- docker exec -t build_img sh -c "
   xbps-install -Suy m4 pkg-config base-devel cmake ninja valgrind-devel doxygen graphviz"
script:
- docker exec -t build_img sh -c "
   cd /travis &&
   make DEBUG=YES BUILD_DOC=YES BUILD_TESTS=YES &&
   make test DEBUG=YES BUILD_DOC=YES BUILD_TESTS=YES &&
   make install DEBUG=YES BUILD_DOC=YES BUILD_TESTS=YES DESTDIR=$(pwd)/install"
