name: PrydeWorX Library CI

on: 
    push:
        branches:
            - master
            - github-actions-test
    pull_request:
        branches:
            - master
            - github-actions-test

defaults:
    run:
        shell: bash

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout library
              uses: actions/checkout@v2
            - name: Add Ninja
              run: sudo apt-get install ninja-build
            - name: Build shared library
              run: make DEBUG=YES BUILD_DOC=YES BUILD_TESTS=YES
            - name: Run tests
              run: make test DEBUG=YES BUILD_DOC=YES BUILD_TESTS=YES
            - name: Install full SDK
              run: make install DEBUG=YES BUILD_DOC=YES BUILD_TESTS=YES DESTDIR=$(pwd)/install

